<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Saipavan" failures="15" tests="27" name="DataProviderBased" time="0.479" errors="0" timestamp="2020-07-03T03:55:58 IST">
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Add" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [60] but found [6]">
      <![CDATA[java.lang.AssertionError: expected [60] but found [6]
at com.testexecution.java.MathsDataprovider.Add(MathsDataprovider.java:19)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- Add -->
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Add" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [60] but found [10]">
      <![CDATA[java.lang.AssertionError: expected [60] but found [10]
at com.testexecution.java.MathsDataprovider.Add(MathsDataprovider.java:19)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- Add -->
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Add" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [60] but found [100]">
      <![CDATA[java.lang.AssertionError: expected [60] but found [100]
at com.testexecution.java.MathsDataprovider.Add(MathsDataprovider.java:19)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- Add -->
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Modulus" time="0.006"/>
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Modulus" time="0.013"/>
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Modulus" time="0.006"/>
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Multiplication" time="0.012"/>
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Multiplication" time="0.004"/>
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Multiplication" time="0.011"/>
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Negate" time="0.007"/>
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Negate" time="0.009"/>
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Negate" time="0.003"/>
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Powerof" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.testexecution.java.MathsDataprovider.Powerof(MathsDataprovider.java:91)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Powerof -->
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Powerof" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.testexecution.java.MathsDataprovider.Powerof(MathsDataprovider.java:91)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Powerof -->
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Powerof" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.testexecution.java.MathsDataprovider.Powerof(MathsDataprovider.java:91)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- Powerof -->
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Powerof1" time="0.005"/>
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Powerof1" time="0.003"/>
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Powerof1" time="0.002"/>
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Sub" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [60] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [60] but found [2]
at com.testexecution.java.MathsDataprovider.Sub(MathsDataprovider.java:31)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- Sub -->
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Sub" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [60] but found [6]">
      <![CDATA[java.lang.AssertionError: expected [60] but found [6]
at com.testexecution.java.MathsDataprovider.Sub(MathsDataprovider.java:31)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- Sub -->
  <testcase classname="com.testexecution.java.MathsDataprovider" name="Sub" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [60] but found [80]">
      <![CDATA[java.lang.AssertionError: expected [60] but found [80]
at com.testexecution.java.MathsDataprovider.Sub(MathsDataprovider.java:31)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- Sub -->
  <testcase classname="com.testexecution.java.MathsDataprovider" name="division" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [22.0] but found [2.0]">
      <![CDATA[java.lang.AssertionError: expected [22.0] but found [2.0]
at com.testexecution.java.MathsDataprovider.division(MathsDataprovider.java:54)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- division -->
  <testcase classname="com.testexecution.java.MathsDataprovider" name="division" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [22.0] but found [4.0]">
      <![CDATA[java.lang.AssertionError: expected [22.0] but found [4.0]
at com.testexecution.java.MathsDataprovider.division(MathsDataprovider.java:54)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- division -->
  <testcase classname="com.testexecution.java.MathsDataprovider" name="division" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [22.0] but found [9.0]">
      <![CDATA[java.lang.AssertionError: expected [22.0] but found [9.0]
at com.testexecution.java.MathsDataprovider.division(MathsDataprovider.java:54)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- division -->
  <testcase classname="com.testexecution.java.MathsDataprovider" name="invert" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [0.99] but found [0.25]">
      <![CDATA[java.lang.AssertionError: expected [0.99] but found [0.25]
at com.testexecution.java.MathsDataprovider.invert(MathsDataprovider.java:67)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- invert -->
  <testcase classname="com.testexecution.java.MathsDataprovider" name="invert" time="0.004">
    <failure type="java.lang.AssertionError" message="expected [0.99] but found [0.04]">
      <![CDATA[java.lang.AssertionError: expected [0.99] but found [0.04]
at com.testexecution.java.MathsDataprovider.invert(MathsDataprovider.java:67)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- invert -->
  <testcase classname="com.testexecution.java.MathsDataprovider" name="invert" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [0.99] but found [0.02]">
      <![CDATA[java.lang.AssertionError: expected [0.99] but found [0.02]
at com.testexecution.java.MathsDataprovider.invert(MathsDataprovider.java:67)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- invert -->
</testsuite> <!-- DataProviderBased -->
