<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Saipavan" failures="2" tests="9" name="com.testexecution.java.MathOpr" time="0.027" errors="0" timestamp="2020-07-03T03:55:59 IST" skipped="0">
  <testcase classname="com.testexecution.java.MathOpr" name="Modulus" time="0.003"/>
  <system-out>
Modulus Function executed  3  </system-out>
  <testcase classname="com.testexecution.java.MathOpr" name="Powerof1" time="0.003"/>
  <system-out>
Power Function executed  256.0  </system-out>
  <testcase classname="com.testexecution.java.MathOpr" name="Multiplication" time="0.003">
    <failure message="expected [512] but found [20]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [512] but found [20]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:839)
at org.testng.Assert.assertEquals(Assert.java:849)
at com.testexecution.java.MathOpr.Multiplication(MathOpr.java:35)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
    </failure>
  </testcase> <!-- Multiplication -->
  <system-out>
Multiplication Function executed  20  </system-out>
  <testcase classname="com.testexecution.java.MathOpr" name="Negate" time="0.003">
    <failure message="expected [false] but found [true]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:968)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at com.testexecution.java.MathOpr.Negate(MathOpr.java:123)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
    </failure>
  </testcase> <!-- Negate -->
  <system-out>
negat Function executed  -178.0  </system-out>
  <testcase classname="com.testexecution.java.MathOpr" name="Add" time="0.003"/>
  <system-out>
TestNG_ReportsAndLogs -> Add60  </system-out>
  <testcase classname="com.testexecution.java.MathOpr" name="Powerof" time="0.002"/>
  <system-out>
Power of  Function executed  81.0  </system-out>
  <testcase classname="com.testexecution.java.MathOpr" name="Sub" time="0.004"/>
  <system-out>
Substraction Function executed  1  </system-out>
  <testcase classname="com.testexecution.java.MathOpr" name="invert" time="0.003"/>
  <system-out>
Inverse Function executed  0.00641025641025641  </system-out>
  <testcase classname="com.testexecution.java.MathOpr" name="div" time="0.003"/>
  <system-out>
Division Function executed  22.0  </system-out>
</testsuite> <!-- com.testexecution.java.MathOpr -->
