<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Saipavan" failures="2" tests="5" name="com.testexecution.java.CalcParellel2" time="0.015" errors="0" timestamp="2020-07-03T03:55:59 IST" skipped="0">
  <testcase classname="com.testexecution.java.CalcParellel2" name="Powerof1" time="0.002"/>
  <system-out>
Exponent Function executed  256.0  </system-out>
  <testcase classname="com.testexecution.java.CalcParellel2" name="Powerof" time="0.002"/>
  <system-out>
Exponent Function executed  81.0  </system-out>
  <testcase classname="com.testexecution.java.CalcParellel2" name="invert" time="0.004">
    <failure message="expected [0.5] but found [0.02]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [0.5] but found [0.02]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:968)
at org.testng.Assert.assertEquals(Assert.java:640)
at org.testng.Assert.assertEquals(Assert.java:651)
at com.testexecution.java.CalcParellel2.invert(CalcParellel2.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
    </failure>
  </testcase> <!-- invert -->
  <system-out>
Invertion  Function executed  0.02  </system-out>
  <testcase classname="com.testexecution.java.CalcParellel2" name="Modulus" time="0.002">
    <failure message="did not expect [3] but found [3]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: did not expect [3] but found [3]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertNotEquals(Assert.java:1404)
at org.testng.Assert.assertNotEquals(Assert.java:1409)
at com.testexecution.java.CalcParellel2.Modulus(CalcParellel2.java:32)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:830)
]]>
    </failure>
  </testcase> <!-- Modulus -->
  <system-out>
Modulus  Function executed  3  </system-out>
  <testcase classname="com.testexecution.java.CalcParellel2" name="Negate" time="0.005"/>
  <system-out>
Negate Function executed  -178.0  </system-out>
</testsuite> <!-- com.testexecution.java.CalcParellel2 -->
